env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    gh_token: "ENCRYPTED[d33aa6d3c484d512e2e653158899c442820ed2d1991157f423e67959292d0297a1f24eae79e5d0e807d67d0fdc31c496]"
    bot_api: "ENCRYPTED[21b145c753e8c20087278af7bd9279d918c1fb2b34867849c67c5bc117a12ec2039ddcd7a793698488492662d7fcdbcb]"
    chat_id: "ENCRYPTED[1268a868d7290ee3ecd8350f35d4fe12fb60e9a63330d2d105a26e507b9479919052cac11930475b6695716370c6632b]"
    rom: "superior"
  
task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - bash build system gh
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache gh # Ccache uploading script
