#!/bin/bash

cd /tmp

up () {
 if [ -e $1 ]; then
  echo "uploading $1"
	curl --retry 18 --upload-file $1 temp.sh
	 #3d, 4000mb limit
  fi
}

# Compress function with pigz for faster compression
com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

# disable ccache upload if rom compilation was successful
if [ ! -e rom/out/target/product/*/*2022*zip ]; then
if [ -d /tmp/ccache ]; then
echo "|| Compressing CCACHE ||"

# First compress in with pigz in a single zip.
time com ccache 1 # Compression level 1, its enough

# Now split in 2GB parts
7za a -tzip -v2048m -mx=0 ccache_backup.zip ccache.tar.gz

# upload all parts
echo "|| Uploading CCACHE ||"
for i in /tmp/ccache_backup.zip.*; do
   time up ${i}
done

sleep 5
echo "|| Uploaded ||"
fi
fi

echo "|| Clean storage ||"
rm -rf /tmp/rom
echo "|| Done ||"
